### ISSUE TITLE
secrets: line 7: g3nq4c78: command not found

### ISSUE THREAD

**Issue by dannymichel** [octavius64/Gazelle#1]
I'm getting the error ``secrets: line 7: g3nq4c78: command not found``

**Comment by octavius64** [comment]
Hey, the docker_compose.sh script simply "sources" the secrets file to read the key-value pairs. Make sure there is no space between the key value pairs because bash doesn't like any spaces. If it still doesn't work, can you please dump the contents of your secrets file here?

**Comment by dannymichel** [comment]
Just to be sure, I used your secrets file with the defaults and it ran but i got 
```
sudo ./docker_compose.sh build
unknown flag: --project-name
See 'docker --help'.
```

**Comment by octavius64** [comment]
Do you have docker compose installed? What does `docker compose --version` print?

**Comment by dannymichel** [comment]
> docker compose --version

Docker version 20.10.8, build 3967b7d

**Comment by octavius64** [comment]
Can you also please run `docker compose --help` and make sure `--project-name` is a valid argument in the help text?

This is the output on my machine:

```
docker compose --help

Usage:  docker compose [OPTIONS] COMMAND

Docker Compose

Options:
      --ansi string                Control when to print ANSI control characters ("never"|"always"|"auto") (default "auto")
      --compatibility              Run compose in backward compatibility mode
      --env-file string            Specify an alternate environment file.
  -f, --file stringArray           Compose configuration files
      --parallel int               Control max parallelism, -1 for unlimited (default -1)
      --profile stringArray        Specify a profile to enable
      --project-directory string   Specify an alternate working directory
                                   (default: the path of the, first specified, Compose file)
  -p, --project-name string        Project name
```

**Comment by dannymichel** [comment]
```
➜  docker git:(main) docker compose --version
Docker version 20.10.8, build 3967b7d
➜  docker git:(main) docker-compose --version
docker-compose version 1.25.3, build d4d1b42b
➜  docker git:(main) 
```

**Comment by octavius64** [comment]
I see, looks like you have `docker-compose` on your machine, which is a separate binary. Can you edit the last line of `docker_compose.sh`?

Old:
```
exec docker compose --project-name gazelle -f docker-compose.yml "$@"
```

New:
```
exec docker-compose --project-name gazelle -f docker-compose.yml "$@"
```

**Comment by dannymichel** [comment]
> I see, looks like you have `docker-compose` on your machine, which is a separate binary. Can you edit the last line of `docker_compose.sh`?
> 
> Old:
> 
> ```
> exec docker compose --project-name gazelle -f docker-compose.yml "$@"
> ```
> 
> New:
> 
> ```
> exec docker-compose --project-name gazelle -f docker-compose.yml "$@"
> ```

That worked
